name: Build APK (new way, but KO)

on: workflow_dispatch

jobs:
  # Build job. Builds app for Android with Buildozer
  build-android:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install docker & git
        run: |
          sudo apt install docker git
          sudo usermod -aG docker $USER
          newgrp docker
          
      - name: build the apk
        run: |
            python3 make.py init
            python3 make.py build

      - name: rename the apk
        run: |
           cd app
           mv bin/*.apk bin/app.apk
        
      # - name: Build with Buildozer
      #   uses: ArtemSBulgakov/buildozer-action@v1
      #   id: buildozer
      #   with:
      #     workdir: ./app
      #     buildozer_version: stable

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: bin/app.apk
